name: pcom_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.8.0

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_easyloading: ^3.0.5
  smooth_page_indicator: ^1.2.0+3
  cached_network_image: ^3.3.1
  qr_flutter: ^4.1.0


  http: ^1.0.0
  open_settings_plus: ^0.4.0
  flutter_secure_storage: ^9.2.4
  logger: ^2.5.0
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  firebase_core: ^3.14.0
  firebase_auth: ^5.5.1
  flutter_local_notifications: ^19.2.1

  gradient_borders: ^1.0.1
  flutter_semi_circle: ^1.0.0

  url_launcher: ^6.2.5

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/app_icon.png"


flutter_native_splash:
  color: "#081035"
  image: assets/images/splash.png
  fullscreen: true

  android_12:
    color: "#081035"
    image: assets/images/splash.png
    fullscreen: true
